# Site settings
title: "The Missing Semester - AIUB"
description: "Bridging the gap between academics and real-world skills."
url: "https://missingsemester.github.io" # Your site's URL
baseurl: "" # Leave empty for GitHub Pages with user/organization site
author: "Tanvir Rahman" # Your name

# Build settings
theme: minima # Default Jekyll theme
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5 # Number of posts per page
paginate_path: "/page:num/"

# Social Links (optional)
twitter_username: "yourtwitterhandle"
github_username: "codewithtanvir"
linkedin_username: "yourlinkedinhandle"

# Defaults
defaults:
  - scope:
      path: "" # All files
      type: "posts"
    values:
      layout: "post"

# Exclusions (files or folders not included in the build)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Custom variables
email: "tanvir.rahman.workmail@gmail.com"
